from . import mail_gateway
from . import mail_thread
from . import bader_inbox
from . import mail_channel
from . import res_partner
from . import mail_whatsapp_template
from . import mail_whatsapp_template_parts
from . import mail_whatsapp_message_status
from . import mail_whatsapp_interactive
from . import mail_whatsapp_flow
from . import mail_whatsapp_catalog
from . import mail_whatsapp_scheduled
from . import mail_whatsapp_automation
from . import mail_whatsapp_agent
from . import mail_whatsapp_analytics
from . import mail_whatsapp_chatbot
from . import mail_whatsapp_campaign
from . import mail_whatsapp_transcription
from . import mail_gateway_evolution
